### ISSUE TITLE
도커(Docker), 쿠버네티스(Kubernetes) 통합 도커 데스크톱을 스테이블 채널에 릴리즈: 대시보드 yaml 업데이트

### ISSUE THREAD

**Issue by Koomook** [44bits/feedback#3]
`$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
` 404 발생
-> `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
` 
참고: k8s web-ui dashboard docs

+ 로그인할 때 token 혹은 config 를 반드시 설정하도록 바뀌었습니다.
https://github.com/kubernetes/dashboard/wiki/Creating-sample-user

**Comment by nacyot** [comment]
동작하는 파일을 확인하고 수정해두겠습니다.

https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.0/src/deploy/recommended/kubernetes-dashboard.yaml

감사합니다!
