### ISSUE TITLE
replay-2018-korea-tech-development-conferences

### ISSUE THREAD

**Issue by SDuck4** [44bits/feedback#4]
https://www.44bits.io/ko/post/replay-2018-korea-tech-development-conferences#%EB%8D%B0%EB%B7%B0-2018deview

> 데뷰는 네이버에서 매년 개최하는 개발자 컨퍼런스입니다. 네이버의 ***노후우***를 비롯해 다양한 기업에서...

'노하우'를 '노후우'로 오타내신 것 같습니다.

**Comment by nacyot** [comment]
늦었지만, 이제라도 수정했습니다! 알려주셔서 감사합니다.
