### ISSUE TITLE
amazon-ecs-iam-role-for-cluster-instance-and-service

### ISSUE THREAD

**Issue by kdhfred** [44bits/feedback#5]
## URI
https://www.44bits.io/ko/post/amazon-ecs-iam-role-for-cluster-instance-and-service

## Bug
`ecs-instance` 라는 이름의 빈 역할을 생성이 의도되었으나
아래의 command line 에서는 `ECSInstance` 로 생성합니다.

![image](https://user-images.githubusercontent.com/7248836/62339558-5a937800-b517-11e9-8c78-7753f320f188.png)

**Comment by velopert** [comment]
```
aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role --role-name ecs-instance
```

`--role-name` 부분을 `ecs-instance`가 아닌 `ECSInstance`로 해야 할 것 같아요 (사전에 입력된 명령어에서 그 이름으로 만들었었기 때문에)

감사합니다.

**Comment by nacyot** [comment]
수정했습니다!

**Comment by sjquant** [comment]
안녕하세요, 좋은 글 잘 읽었습니다. 해당 글에 나온 방법으로 ecs-instance Role을 만드니까
[이 글](https://www.44bits.io/ko/post/container-orchestration-101-with-docker-and-aws-elastic-container-service)에서 인스턴스 생성시에 `An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value (ecs-instance) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name` 과 같은 에러가 발생하네요. 근데 웹콘솔을 통해 만들어진 ecsInstanceRole을 넣으면 잘 작동합니다. IAM에서 확인해보면 다른게 없는거 같은데 왜 그럴까요...? 제가 뭔가 잘못적용한거 같은데... 도무지 못찾겠어서 질문 남깁니다.

**Comment by nacyot** [comment]
sjquant // 좀 더 확인해봐야겠지만 내용이 잘못됐을 수도 있을 것 같네요. 인스턴스 생성하는 부분에는 IAM Role이 아니라 인스턴스 프로필을 별도로 만들어서 넣어야할 것 같은데, 설명이 빠진 느낌이네요. 시간 나는대로 테스트 후에 남겨두겠습니다~

**Comment by kimeuichan** [comment]
안녕하세요. 좋은글 감사합니다.

출처를 밝히고 정리글을 작성하고 싶은데 사용해도 괜찮을까요?

**Comment by nacyot** [comment]
kimeuichan // 안녕하세요. 네. 괜찮습니다.
