### ISSUE TITLE
deprecated duplicate — use #72

### ISSUE THREAD

**Issue by kdhfred** [44bits/feedback#6]
## URI
https://www.44bits.io/ko/post/container-orchestration-101-with-docker-and-aws-elastic-container-service

## Fix
iam-instance-profile 에 Role을 넣어주면 
```bash
An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value (ECSInstance) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
```
이러한 에러를 뱉습니다.

https://docs.aws.amazon.com/ko_kr/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html

instance profile 이라는 별도의 인스턴스 프로필을 생성해서 Role을 attach 시킨 후 사용해야합니다.

``` bash
$ aws iam create-instance-profile --instance-profile-name ecs-instance
$ aws iam add-role-to-instance-profile --instance-profile-name ecs-instance --role-name ecs-instance
```

이렇게 instance-profile을 만든 후에 `--iam-instance-profile Name=ecs-instance` 를 넣었더니 이슈가 해결되었습니다.

## Section
![image](https://user-images.githubusercontent.com/7248836/62340170-8a437f80-b519-11e9-9143-68f258fe99b4.png)

**Comment by nacyot** [comment]
이 케이스는 직접 만든 ecs-instance 롤이 아니라 ECSInstance 롤을 사용했던 것 같아요. 가정이 다른 상태라, 우선 수정하지 않기로 했습니다. 이슈는 우선 닫아두겠습니다. 혹시 맘에(?) 걸리시는 분이 있으면 다시 열어주세요.
