### ISSUE TITLE
cli_json_processor_jq_basic_syntax

### ISSUE THREAD

**Issue by zzerjae** [44bits/feedback#7]
**배열 인덱스 필터: [n]** 문단 중에서,

두 번째 코드 설명 부분에서

```
$ echo '{"data": [0, 11, 22, 33, 44 ,55]'} | jq '.data | .[4]'
44
```
`$ echo '{"data": [0, 11, 22, 33, 44 ,55]'} | jq '.data | .[4]'`
가 아래와 같이 수정되어야 합니다.
`$ echo '{"data": [0, 11, 22, 33, 44 ,55]}' | jq '.data | .[4]'`

**Comment by nacyot** [comment]
수정했습니다! 확인해주셔서 감사합니다.

https://www.44bits.io/ko/post/cli_json_processor_jq_basic_syntax
