### ISSUE TITLE
aws-aurora-launches-global-database-to-seoul-region

### ISSUE THREAD

**Issue by kakao-kong-j** [44bits/feedback#8]
## 재현

https://www.44bits.io/ko/post/aws-aurora-launches-global-database-to-seoul-region 해당 글을 보던중 하단에 buymeacoffee url 이 유효하지 않는 것을 발견하였습니다.

## 결과

https://www.buymeacoffee.com/44bits  url 이 유효하지 않습니다.

**Comment by raccoonyy** [comment]
알려주셔서 고맙습니다.
<http://buymeacoffee.com/stdoutfm>로 바꾸었는데 반영하질 못했네요.
수정해두겠습니다.

**Comment by nacyot** [comment]
buymecoffee는 내부 정책 변경으로 계정을 만들더라도 Paypal 출금이 불가능한 상태입니다 ㅜ

http://buymeacoffee.com/stdoutfm 을 사용할지는 추후에 결정하고, 우선은 링크를 제외하도록 하겠습니다.
